name: qagency
description: "Q Agency Flutter Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  logger: ^2.4.0
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  shimmer: ^3.0.0
  drift: ^2.20.2
  drift_flutter: ^0.1.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.20.3
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: SFPro
      fonts:
        # Using only Display-Regular because it's the only font in the design
        - asset: assets/fonts/SF-Pro-Display-Regular.otf