name: qagency
description: "Q Agency Flutter Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: SFPro
      fonts:
        # Using only Display-Regular because it's the only font in the design
        - asset: assets/fonts/SF-Pro-Display-Regular.otf